name: SAST Semgrep

on:
  pull_request: {}
  push:
  schedule:
    - cron: '20 08 * * *'
env:
  KIBANA_BASE: ''
  
jobs:
  semgrep:
    name: Scan
    permissions:
      security-events: write
      actions: read
      contents: read
    if: (github.actor != 'dependabot[bot]')
    uses: a-yohan/sast-report-action/.github/workflows/semgrep.yml@main
    with:
      url: ${{ secrets.ES_HOST }}
      user: ${{ secrets.ES_USERNAME }}
      password: ${{ secrets.ES_PASSWORD }}
      disable_ssl_validation: true
      kibana_base_path: ${{ env.KIBANA_BASE }}
