name: SAST Semgrep

on:
  pull_request: {}
  push:
  schedule:
    - cron: '20 08 * * *'

env:
  RESULTS_FILE: results.json

jobs:
  semgrep:
    name: Scan
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3

      - name: Clone Rules
        uses: sast-report-action/.github/workflows/semgrep.yml@main
        with:
          json_file: ${{ env.RESULTS_FILE }}
          url: ${{ secrets.ES_HOST }}
          user: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          disable_ssl_validation: true
          kibana_base_path: ${{ env.KIBANA_BASE }}
